# Partial config, see full documentation in the README.md

default-base = "HEAD"

[plan]
judge-extra-prompt = """
  You must reject the plan if:
    - The plan proposes writing tests.
    - The plan proposes to run a linter, type checker, or formatter.
    - The plan proposes to remove unused imports (unless they are *preventing compilation*, rather than just being unused).
    - The plan proposes to run automatic tests or do testing manually, including "basic sanity checks" or "smoke testing".
    - The plan proposes to run the agent tool itself (src/main.py).
    - The plan proposes using `pip` or `poetry` (this project uses `uv`).
  
  If rejecting the plan, you must explain in detail why you are rejecting it.
  You must also give the planner the entire rejection criteria from the above, so that it will adhere to all of them in the next planning round.
"""
