"$schema" = "./config.schema.json"

# Partial config, see full documentation in the README.md

default-base = "HEAD"

post-implementation-hook-command = """
  MISE_TRUSTED_CONFIG_PATHS=$(pwd)/mise.toml mise run format
"""

[plan]
planner-extra-prompt = """
  Do not propose writing tests, running automatic tests, or doing testing manually.
  If you do, your plan will be rejected.
  The exception is if the **task** explicitly asks to write or run tests.

  Please include this step in your plan: `uv run pyright --project .`.
  It must pass before the task is considered complete.

  Please include updating the changelog in your plan, if the task results in a change to the codebase.
  The changelog entry for your changes must start with "(AGENT)".

  Please note in your plan that all agent-generated commits must start with (AGENT) in the commit message,
  and the task statement (cleaned up if needed) in the commit message body.
"""

judge-extra-prompt = """
  You must reject the plan if:
  - The plan proposes writing tests for anything other than pure functions that can be easily unit-tested.
  - The plan proposes to run automatic tests or do testing manually, including "basic sanity checks" or "smoke testing".
    Note that linters or type checkers *are allowed*.
    Running tests written for pure functions is also allowed.
  - The plan proposes to run the agent tool itself (src/agent/main.py).
  - The plan proposes using `pip` or `poetry` (this project uses `uv`).
  - The plan proposes pushing commits or creating pull requests.
  - The plan proposes to edit `config.schema.json` (it is generated from Pydantic models).

  The exception is if the **task** explicitly asks to do any of these things.
  For example, if the task is "write a test for function Abc", then the plan can include writing and running a test for function `Abc`.

  If rejecting the plan, you must explain in detail why you are rejecting it.
  You must also give the planner the entire rejection criteria from the above, so that it will adhere to all of them in the next planning round.
"""

[implement]
completion.judge-extra-prompt = """
  You must not accept the implementation until:

  - You run `uv run pyright --project .` and it passes without errors.
  - You run `uv run pytest -v` and it passes without errors.
  - The changelog has been updated accordingly (if the task results in a change to the codebase).
"""
