"$schema" = "./config.schema.json"

# Partial config, see full documentation in the README.md

default-base = "HEAD"

post-implementation-hook-command = """
  ruff format || true;
  fd .py | xargs uvx --isolated autoimport;
  """

[plan]
planner-extra-prompt = """
  Do not propose writing tests, running automatic tests, or doing testing manually.
  If you do, your plan will be rejected.
  The exception is if the **task** explicitly asks to write or run tests.

  Please include these two checks:
    - `ruff check` to check for syntax errors and lints
    - `uv run pyright --project .` to typecheck
  Both must pass before the task is considered complete.
"""

judge-extra-prompt = """
  You must reject the plan if:
    - The plan proposes writing tests.
    - The plan proposes to run automatic tests or do testing manually, including "basic sanity checks" or "smoke testing".
      Note that linters or type checkers *are allowed*.
    - The plan proposes to run the agent tool itself (src/agent/main.py).
    - The plan proposes using `pip` or `poetry` (this project uses `uv`).
    - The plan proposes pushing commits or creating pull requests.

  The exception is if the **task** explicitly asks to do any of these things.
  For example, if the task is "write a test for function Abc", then the plan can include writing and running a test for function `Abc`.

  If rejecting the plan, you must explain in detail why you are rejecting it.
  You must also give the planner the entire rejection criteria from the above, so that it will adhere to all of them in the next planning round.
"""
