"$schema" = "./config.schema.json"

# Partial config, see full documentation in the README.md

post-implementation-hook-command = """
  MISE_TRUSTED_CONFIG_PATHS=$(pwd)/mise.toml mise run format
  MISE_TRUSTED_CONFIG_PATHS=$(pwd)/mise.toml mise run generate-schema
"""

post-implementation-check-command = """
  MISE_TRUSTED_CONFIG_PATHS=$(pwd)/mise.toml mise run --jobs=1 check:ai
"""

[plan]
planner-extra-prompt = """
  Do not propose doing testing manually.
  If you do, your plan will be rejected.
  The exception is if the **task** explicitly asks to write or run tests.

  Read the .clinerules file before writing your plan.
  It contains important rules and helpful knowledge about the project.
"""

judge-extra-prompt = """
  You must reject the plan if:

  - The plan proposes writing tests that are not very similar to the ones that already exist.
    For example, adding a test to `tests/git_utils.py` is fine.
    Writing an integration test or a test involving network is not fine, since we don't have any tests like that yet.
  
  - The plan proposes to do testing manually, including "basic sanity checks" or "smoke testing" or "visual inspection".
    Note that linters or type checkers *are allowed*. Running existing tests is also allowed.

  - The plan proposes to run the agent tool itself (`src/ok/main.py`).

  - The plan proposes using `pip` or `poetry` (this project uses `uv`).
    Also, dependencies must be added with `uv add`, not `uv pip`.
  
  - The plan proposes pushing commits or creating pull requests.
  
  - The plan proposes to edit `config.schema.json` (it is generated from Pydantic models).

  The exception is if the **task** explicitly asks to do any of these things.
  For example, if the task is "write a test for function Abc", then the plan can include writing and running a test for function `Abc`.

  If rejecting the plan, you must explain in detail why you are rejecting it.
  For each objection, you must provide the relevant rule from the judging criteria *and* concretely explain how the plan violates it.
"""
