[tools]
python = "3.13.5"
uv = "0.7.18"
"pipx:ty" = "latest"

[tasks.run]
description = "Run the agent"
run = "uv run agent"

[tasks.add-types]
description = "Auto-add types to the Python files"
run = [
  'jj x fd .py -x uv run --with=autotyping --isolated python -m autotyping {} --safe',
]

[tasks.pyright]
description = "Run pyright to check types in the Python files"
run = "uv run pyright --project ."

[tasks.ty]
description = "Run ty to check types in the Python files"
run = "ty check"

[tasks.autoimport]
description = "Add missing imports to the Python files"
run = """
  jj x 'fd .py | xargs uvx --isolated autoimport'
"""

[tasks.cleanup]
run = [
  "jj x 'ruff check --fix; ruff format'",
  "jj abandon 'mutable() & empty()'",
]

[tasks.clean-branches]
description = "Remove all branches below main/dev"
run = '''
  jj bookmark list -r '::(main|dev)' -T'self++"\n"' | grep -Ev '^(main|dev)$' | xargs jj bookmark delete
'''
