# Auto-activate the venv so that `python` and `python3` work even without `uv run`.
settings.python.uv_venv_auto = true

[tools]
python = "3.13.5"
uv = "0.7.18"
"pipx:ty" = "latest"
taplo = "latest"
dprint = "latest"
# "npm:opencode-ai" = "0.1.194"  # we need the version with print flag, see tasks.build-opencode

[tasks.ok]
description = "Run the agent"
run = "uvx --isolated --from . --refresh -- ok"

[tasks.check]
description = "Run all checks and tests"
depends = ["lint", "pyright", "check-schema", "test"]

[tasks."check:ai"]
description = "Run only the checks that we want agents to run (don't hassle them about import ordering, etc.)"
depends = ["lint:ai", "pyright", "test"]

[tasks.logs]
description = "Show the logs of the agent (~/.ok/logs/)"
quiet = true
usage = """
  flag "--file <file>" "The log file to view (default: latest log file in ~/.ok/logs/)"
  arg "[eliot_tree_args]" var=#true "Additional arguments for eliot-tree"
"""
run = """
  if [[ -z "$usage_file" ]]; then
    usage_file=~/.ok/logs/"$(ls -t ~/.ok/logs/ | head -n 1)"
  fi
  echo "--- $usage_file ---"
  eval "args=(${usage_eliot_tree_args:-})"
  cat "$usage_file" \
    | jq -c 'del(.state.steps_log, .result.steps_log, .state.attempts_log, .result.attempts_log, .event)' 2>/dev/null \
    | jq -c 'select(.message_type // "" | startswith("log.") | not)' \
    | uv run eliot-tree "${args[@]}"
  echo "--- $usage_file ---"
"""

[tasks."logs:full"]
description = "Show the logs of the agent (~/.ok/logs/) without filtering"
quiet = true
usage = """
  flag "--file <file>" "The log file to view (default: latest log file in ~/.ok/logs/)"
  arg "[eliot_tree_args]" var=#true "Additional arguments for eliot-tree"
"""
run = """
  if [[ -z "$usage_file" ]]; then
    usage_file=~/.ok/logs/"$(ls -t ~/.ok/logs/ | head -n 1)"
  fi
  echo "--- $usage_file ---"
  eval "args=(${usage_eliot_tree_args:-})"
  uv run eliot-tree "$usage_file" "${args[@]}"
  echo "--- $usage_file ---"
"""

[tasks.format]
description = "Format everything"
run = "dprint fmt"

[tasks.generate-schema]
description = "Generate config.schema.json from Pydantic"
run = "uv run scripts/generate_schema.py"

# Cleanup / autofix

[tasks.x-add-types]
description = "Auto-add types to the Python files, across all commits"
run = [
    'jj x fd .py -x uv run --with=autotyping --isolated python -m autotyping {} --safe',
]

[tasks.xformat]
description = "Run 'format' across all commits"
run = """jj x 'MISE_TRUSTED_CONFIG_PATHS=$(pwd)/mise.toml mise run format'"""

[tasks."rm-branches"]
description = "Remove all agent branches (bookmarks)"
run = '''
  jj bookmark list -T'self++"\n"' | grep -E '^ok/' | xargs jj bookmark delete
'''

# Checks

[tasks.test]
description = "Run all tests"
run = ["uv run pytest -v"]

[tasks.check-schema]
description = "Check that the checked-in schema matches Pydantic and the current .ok.toml"
run = ["uv run scripts/generate_schema.py --diff", "taplo validate .ok.toml"]

[tasks.lint]
description = "Run ruff to check the Python files"
run = "ruff check"

[tasks."lint:ai"]
description = "Run ruff to check the Python files, but don't hassle agents about import ordering, etc."
# E402 = import ordering
run = "ruff check --exclude E402"

[tasks.pyright]
description = "Run pyright to check types in the Python files"
run = "uv run pyright --project ."

# Misc

[tasks.ty]
description = "Run ty to check types in the Python files (doesn't fully work yet)"
run = "ty check"

# https://github.com/sst/opencode/pull/533

[tasks.build-opencode]
description = "Build a specific commit of Opencode CLI and install it to ~/.ok/bin/opencode"
tools.bun = "1.2.18"
tools.go = "1.24.4"
run = "uv run scripts/build_opencode.py"

[tasks."logs:find-lints"]
description = "Find all lints and errors in agent logs"
run = '''
  for f in ~/.ok/logs/*.json ~/.agent/logs/*.json; do
    gron -s $f
  done | rg --pcre2 '\\n\\n([^ ]+\.py)(:\d+:(\d+:)?) *(.*?)\\n' -or '$4' | sort | uniq -c | sort -nr
'''
tools.gron = "latest"
tools.rg = "latest"
