line-length = 120

[lint]
extend-select = [
  "TID252", # Use absolute imports
  # "PTH", # Use pathlib
  "B", # Just nice rules, https://docs.astral.sh/ruff/rules/#flake8-bugbear-b
  # "FBT", # Positional bools
  "ASYNC", # Async functions
]

[lint.flake8-tidy-imports]
ban-relative-imports = "all"
